dist: xenial
sudo: required
cache:
  directories:
      - $HOME/.m2
      - $HOME/.ccache
      - $HOME/downloads
  timeout: 1000
language: java
services:
      - docker

jobs:
   include:
      - stage: Deploy
      - os: linux
        env: PROJ=ffmpeg OS=linux-x86_64 EXT=-gltranstion
        install: true
        script: ./ci/install-travis.sh

      - os: osx
        osx_image: xcode10.1
        env: PROJ=ffmpeg OS=macosx-x86_64 EXT=-gltranstion
        install: true
        script: ./ci/install-travis.sh

      - stage: Redeploy
        os: linux
        install: true
        script: ./ci/redeploy.sh
